---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sky-devops-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry
      containers:
      - name: sky-devops-container
        image: girishh222/girish5:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

----

apiVersion: v1
kind: Service
metadata:
 name: my-skydevops-service
 labels:
   app: my-app
spec:
 type: NodePort
 ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30011
 selector:
   app: my-app

...

apiVersion: v1
kind: Secret
metadata:
 name: my-registry
data:
  .dockerconfigjson: Z2lyaXNoaDIyMjo5OTAxNDU5NDI5QnM=
type: kubernetes.io/dockerconfigjson

...
